apiVersion: v1
kind: Secret
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: "wordpress-jpk-lab"
    app.kubernetes.io/instance: "lab6-instance"
type: Opaque
data:
  password: c3VwZXJzZWNyZXRwYXNzdzByZA==
