apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app.kubernetes.io/name: "wordpress-jpk-lab"
    app.kubernetes.io/component: server
spec:
  type: NodePort
  ports:
    - port: 30180
      targetPort: 80
  selector:
      app_name: wordpress-site
      env: dev
