apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app.kubernetes.io/name: "wordpress-jpk-lab"
    app.kubernetes.io/component: server 
spec:
  type:
  ports:
  - NodePort: 30180
    containerPort: 80
  selector:
    matchLabels:
      app_name: wordpress-site
      env: dev 
