apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app.kubernetes.io/name: "wordpress-jpk-lab"
    app.kubernetes.io/instance: "lab6-instance"
    app.kubernetes.io/component: database
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  selector:
      app_name: wordpress-site
      env: dev
